### ISSUE TITLE
cannot import name 'safer_name' from 'wheel.bdist_wheel'

### ISSUE THREAD

**Issue by mercurytoxic** [spesmilo/electrum-ecc#3]
https://github.com/spesmilo/electrum-ecc/blob/b2cde56af85becb9582d4fe81c447d41868c246d/setup.py#L14

While trying to compile electrum-ecc on Archlinux I get this error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 13, in <module>
ImportError: cannot import name 'safer_name' from 'wheel.bdist_wheel' (/usr/lib/python3.12/site-packages/wheel/bdist_wheel.py)

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

I noted that the function safer_name is part of the module **_bdist_wheel** and NOT part of the module **bdist_wheel** as referenced in the above line.

**Comment by ecdsa** [comment]
> I noted that the function safer_name is part of the module _bdist_wheel and NOT part of the module bdist_wheel as referenced in the above line.

How did you find that? Do you really have a `_bdist_wheel.py` module in `/usr/lib/python3.12/site-packages/wheel/`?
AFAICT `_bdist_wheel` is just the name under which the class `bdist_wheel` is imported.

**Comment by mercurytoxic** [comment]
Yes I do. On Archlinux's python-wheel 0.44.0-2

```
$ find /usr/lib/python3.12/site-packages/wheel/ -name "*bdist_wheel.py"
/usr/lib/python3.12/site-packages/wheel/_bdist_wheel.py
/usr/lib/python3.12/site-packages/wheel/bdist_wheel.py
```

Another way to see it is listing the modules from the package wheel with:
```
import pkgutil
import wheel

modules = [module.name for module in pkgutil.iter_modules(wheel.__path__)]
print(modules)
```
which gives:

```
$ python src/electrum-ecc-0.0.3/test-2.py 
['__main__', '_bdist_wheel', '_setuptools_logging', 'bdist_wheel', 'cli', 'macosx_libfile', 'metadata', 'util', 'wheelfile']
```

If you list the functions of wheel.bdist_wheel with : 

```
import wheel.bdist_wheel

print(dir(wheel.bdist_wheel))
```
You get:

`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__warningregistry__', 'bdist_wheel', 'warn']`

But if you list the ones from wheel._bdist_wheel you get: 

`['BytesGenerator', 'Callable', 'Command', 'EmailPolicy', 'Generator', 'Iterable', 'Literal', 'PY_LIMITED_API_PATTERN', 'Sequence', 'TYPE_CHECKING', 'WheelFile', 'ZIP_DEFLATED', 'ZIP_STORED', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_is_32bit_interpreter', '_packaging_version', 'annotations', 'bdist_wheel', 'cast', 'get_abi_tag', 'get_flag', 'get_platform', 'iglob', 'log', 'os', 'pkginfo_to_metadata', 'python_tag', 're', 'remove_readonly', 'remove_readonly_exc', 'rmtree', 'safe_name', 'safe_version', 'safer_name', 'safer_version', 'setuptools', 'setuptools_major_version', 'shutil', 'stat', 'struct', 'sys', 'sysconfig', 'tags', 'warnings', 'wheel_version']`

which includes the above mentioned **safer_name** function.

A brief google of packages with leading underscores :
[Non-Public Modules](https://realpython.com/python-double-underscore/#:~:text=Non%2DPublic%20Modules,-You%20should%20know&text=In%20your%20own%20Python%20projects,modules%20directly%20in%20their%20code.)

Non-Public Modules
...
_In your own Python projects, you may have modules that provide code for internal use only. In those cases, you can use a leading underscore in their names to tell other developers that they shouldn’t use these modules directly in their code._

**Comment by ecdsa** [comment]
ok, I guess we should not expect that function to be available.
Maybe we could redeclare `safer_name` in our `setup.py`:

```python
import pkg_resources
def safer_name(name):
    return pkg_resources.safe_name(name).replace('-', '_')
```

does that fix it for you, or are there other imports that are failing?

**Comment by SomberNight** [comment]
Looks like this is a change in wheel 0.44, which started deprecating the bdist_wheel module.
See https://github.com/pypa/wheel/pull/631

also ref: https://github.com/pypa/setuptools/pull/4369

**Comment by SomberNight** [comment]
I think it should be fixed with https://github.com/spesmilo/electrum-ecc/commit/0be1ca2d8112ee0a3667467993685b43d94ebe3c.
Thanks for the report.
