### ISSUE TITLE
Does tested_libversions need updating?

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum-ecc#4]
Hi! I'm trying to launch electrum from source on macos, and it can't find libsecp256k1
When I do brew install secp256k1, it installs the recent libsecp256k1 0.6.0 released two weeks ago: https://github.com/bitcoin-core/secp256k1/releases/tag/v0.6.0
So inside the folder, I see libsecp256k1.5.dylib
But tested versions are up to 2 only. 
See https://github.com/spesmilo/electrum-ecc/blob/b2cde56af85becb9582d4fe81c447d41868c246d/src/electrum_ecc/ecc_fast.py#L48
When on ubuntu, I usually just run
`sudo apt install libsecp256k1-dev`
And because of ubuntu slow rollover of packages I guess, the max version I would get is the number 2
Can this list be updated? Is it like, to prevent breaking ABI changes? Or any blocker in recent libsecp which prevents it from using?
Because when I manually added tested versions it does start at least (:

Hmm but also, I tried compiling the 0.5.1 version, and it has ABI version of 2. So I'm not sure, maybe it's their bug that they jumped 3 versions at once?

EDIT: just tested on linux, and it's also a jump of 3 versions there

**Comment by SomberNight** [comment]
They only bump the ABI version when they make an incompatible change to it. So 0.3.x, 0.4.x, and 0.5.x all used version 2. Now there was a change in 0.6.0, so the ABI version got bumped to 5.
See [the changelog](https://github.com/bitcoin-core/secp256k1/blob/8deef00b33ca81202aca80fe0bcd9730f084fbd2/CHANGELOG.md#060---2024-11-04) re "ABI Compatibility".

The versions themselves are calculated in a somewhat weird way, see https://github.com/bitcoin-core/secp256k1/pull/1055#issuecomment-1227505189

**Comment by Midar** [comment]
This just hit Fedora 42, breaking Electrum there. Do I see it right that at least for what libsecp256k1 is used, just adding 5 to tested versions is fine? I might just patch it in Fedora then to unbreak Electrum.

**Comment by SomberNight** [comment]
Yes, abi versions 2 and 5 do not differ as far as electrum-ecc is concerned.

Instead of patching, you could also update electrum-ecc to 0.0.4. Or maybe I misunderstand -- how exactly do you install libsecp / electrum-ecc / electrum? Note that the latest release of electrum still does not use this library, only the master branch does.

Ahh actually that's probably what is going on then -- you mean patching https://github.com/spesmilo/electrum/blob/657199155526b825735dcd3e11aeb8179d5a91de/electrum/ecc_fast.py#L42

**Comment by Midar** [comment]
Yes, that's what I mean :). Thanks, that was how it looked to me, too. I pushed the updated / fixed package to Fedora 42.
